name = "teakzc/hydrogen"
version = "0.2.0"
description = "Light-weight module initializer."
authors = ["teakzc"]
repository = "https://github.com/teakzc/hydrogen"
license = "MIT"

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = ["src"]