name = "teakzc/hydrogen"
version = "0.2.0"
description = "Light-weight module loader framework"
license = "MIT"
authors = ["teakzc"]
repository = "https://github.com/teakzc/hydrogen"
private = false
includes = ["pesde.toml", "README.md", "LICENSE.md", "src/**"]

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = ["src"]
