site_name: ByteNet
repo_name: ffrostfall/ByteNet
repo_url: https://github.com/ffrostflame/ByteNet

nav:
  - Home: index.md
  - Documentation:
    - Packets:
      - definePacket: api/functions/definePacket.md
    - DataTypes:
      - Primitives: api/dataTypes/Primitives.md
      - Specials: api/dataTypes/Specials.md


theme:
  name: material
  favicon: assets/favicon.png
  logo: assets/bytenetLogo.png
  palette:
    scheme: slate
    primary: custom
    accent: white
  font:
    text: Arial
    code: Fira Code
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.instant
    - navigation.indexes
    - search.suggest
    - search.highlight
  icon:
    repo: octicons/mark-github-16

extra_css:
  - css/colors.css
  - css/codeblocks.css
  - css/global.css
  - css/homepage.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.extra
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg